# Generated by Django 5.2.7 on 2025-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('legal_address', models.CharField(max_length=150)),
                ('actual_address', models.CharField(max_length=150)),
            ],
        ),
    ]
