# Generated by Django 5.2.7 on 2025-11-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultation_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('подтверждена', 'Подтверждена'), ('ожидает', 'Ожидает'), ('начата', 'Начата'), ('завершена', 'Завершена'), ('оплачена', 'Оплачена'), ('создана', 'Создана')], default='создана', max_length=20),
        ),
    ]
